variables:
  GIT_STRATEGY: clone

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "release"
      when: always
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - if: $CI_COMMIT_TAG
      when: never

default:
  image: python:3.7

stages:
  - test
  - release


#################################################################
# test stage jobs
#################################################################

# YAML anchor containing arrays elements to be merged
# https://stackoverflow.com/questions/24090177/how-to-merge-yaml-arrays/30683699#57209078
# note: no dash before commands
.setup-test-stage: &setup-test-stage |
  # This step installs tox and poetry but it may already be installed in the python docker image
  make setup-cicd-test-stage-gitlab
  . $HOME/.poetry/env

py38:
  stage: test
  image: python:3.8
  before_script:
    - *setup-test-stage
  script:
    - make deps-test
    - make test

py37:
  stage: test
  image: python:3.7
  before_script:
    - *setup-test-stage
  script:
    - make deps-test
    - make test

py36:
  stage: test
  image: python:3.6
  before_script:
    - *setup-test-stage
  script:
    - make deps-test
    - make test

bdd-py38:
  stage: test
  image: python:3.8
  before_script:
    - *setup-test-stage
  script:
    - make deps-bdd
    - make bdd
  artifacts:
    paths:
      - cucumber-report.json
    when: always

bdd-py37:
  stage: test
  image: python:3.7
  before_script:
    - *setup-test-stage
  script:
    - make deps-bdd
    - make bdd

bdd-py36:
  stage: test
  image: python:3.6
  before_script:
    - *setup-test-stage
  script:
    - make deps-bdd
    - make bdd

format:
  stage: test
  before_script:
    - *setup-test-stage
  script:
    - make deps-format
    - make format-check

lint:
  stage: test
  before_script:
    - *setup-test-stage
  script:
    - make deps-lint
    - make lint

type:
  stage: test
  before_script:
    - *setup-test-stage
  script:
    - make deps-type
    - make type

#################################################################
# release stage jobs
#################################################################

semantic_release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TITLE =~ /^chore\(release\): \d*\.\d*\.\d.*/'
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
  image: node:12-buster
  before_script:
    - make setup-cicd-release-stage-gitlab
    - . $HOME/.poetry/env
  script:
    - make cicd-release
